import type { StoreData } from "./types";

const now = () => new Date().toISOString();

export function createSeedData(): StoreData {
  const ts = now();

  const categories = [
    {
      id: "cat-extensions",
      name: "Facebook Extensions Tools",
      slug: "facebook-extensions-tools",
      description: "Browser extensions for Facebook ads & community workflows.",
      sortOrder: 1,
      isPublished: true,
      accent: "indigo",
    },
    {
      id: "cat-bookmark",
      name: "Facebook Bookmark Tools",
      slug: "facebook-bookmark-tools",
      description: "One-click bookmarklets for Facebook Business tools.",
      sortOrder: 2,
      isPublished: true,
      accent: "amber",
    },
    {
      id: "cat-id-tools",
      name: "Facebook ID Tools",
      slug: "facebook-id-tools",
      description: "Online checkers for UID, BM, and Facebook IDs.",
      sortOrder: 3,
      isPublished: true,
      accent: "emerald",
    },
    {
      id: "cat-generators",
      name: "Creative Generators",
      slug: "creative-generators",
      description: "Ad creative tools including Adsterra play-button generator.",
      sortOrder: 0,
      isPublished: true,
      accent: "rose",
    },
  ];

  const tools = [
    {
      id: "tool-adsterra",
      categoryId: "cat-generators",
      name: "Adsterra Image Generator",
      slug: "adsterra-image-generator",
      shortDescription:
        "Resize for Facebook ads and add a pixel-perfect play button so creatives look like real videos.",
      fullDescription:
        "Upload any image, auto-resize to Facebook feed sizes (1200×628, 1080×1080, 1080×1920), and overlay a centered play button that looks like a native video thumbnail. Built for Adsterra / Facebook ads creatives.",
      releaseNotes: "v1.0.0 — Initial release with FB feed presets and play overlay.",
      version: "1.0.0",
      toolType: "generator" as const,
      onlineRoute: "/tools/adsterra-image-generator",
      isPublished: true,
      sortOrder: 0,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-post-booster",
      categoryId: "cat-extensions",
      name: "FB Boost Tools",
      slug: "fb-boost-tools",
      shortDescription: "Facebook post booster Chrome extension — download ZIP.",
      fullDescription:
        "FB Boost Tools (Basictrick).\n\nDownload the ZIP, then Chrome → Extensions → Developer mode → Load unpacked.",
      releaseNotes: "v5.4 — Sky-blue UI. Direct download, no license gate.",
      version: "5.4",
      toolType: "download" as const,
      downloadUrl: "/api/extension/download?tool=boost",
      isPublished: true,
      sortOrder: 0,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-fb-reset",
      categoryId: "cat-extensions",
      name: "FB Reset Tools",
      slug: "fb-reset-tools",
      shortDescription: "Facebook reset extension — download ZIP when ready.",
      fullDescription:
        "FB Reset Tools (Basictrick).\n\nDownload the ZIP when published. Chrome → Extensions → Developer mode → Load unpacked.",
      releaseNotes: "v1.0 — Download slot. Extension zip coming next.",
      version: "1.0",
      toolType: "download" as const,
      downloadUrl: "/api/extension/download?tool=reset",
      isPublished: true,
      sortOrder: 1,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-cookie-ext",
      categoryId: "cat-extensions",
      name: "Cookie Helper Extension",
      slug: "cookie-helper-extension",
      shortDescription: "Quick cookie export/import helper for Facebook sessions (community build).",
      fullDescription:
        "Community Chrome extension for managing Facebook cookies safely on your own accounts. Install via developer mode.",
      releaseNotes: "v1.0.0 — First public drop for Basictrick members.",
      version: "1.0.0",
      toolType: "download" as const,
      downloadUrl: "",
      isPublished: true,
      sortOrder: 2,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-bm-bookmark",
      categoryId: "cat-bookmark",
      name: "Open BM Settings Bookmark",
      slug: "open-bm-settings-bookmark",
      shortDescription: "Jump straight to Business Manager settings.",
      fullDescription: "Drag this bookmarklet to your bookmarks bar to open BM settings instantly.",
      releaseNotes: "v1.0.0 — Initial bookmarklet.",
      version: "1.0.0",
      toolType: "bookmark" as const,
      bookmarkCode:
        "javascript:(function(){window.open('https://business.facebook.com/settings','_blank')})();",
      isPublished: true,
      sortOrder: 1,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-live-uid",
      categoryId: "cat-id-tools",
      name: "Check Live UID Facebook",
      slug: "check-live-uid",
      shortDescription: "Bulk check if Facebook UIDs are live or dead.",
      fullDescription:
        "Paste UIDs (one per line) and verify live/dead status using public Graph picture probes. No Meta Developer App required.",
      releaseNotes: "v1.0.0 — Tokenless live/dead checker.",
      version: "1.0.0",
      toolType: "online" as const,
      onlineRoute: "/tools/check-live-uid",
      isPublished: true,
      sortOrder: 1,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-live-bm",
      categoryId: "cat-id-tools",
      name: "Check Live BM",
      slug: "check-live-bm",
      shortDescription: "Check Business Manager live/dead status in bulk.",
      fullDescription: "Enter BM IDs to probe public availability status.",
      releaseNotes: "v1.0.0 — Best-effort public BM probe.",
      version: "1.0.0",
      toolType: "online" as const,
      onlineRoute: "/tools/check-live-bm",
      isPublished: true,
      sortOrder: 2,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-bm-verified",
      categoryId: "cat-id-tools",
      name: "Check BM Verified",
      slug: "check-bm-verified",
      shortDescription: "Check Business Manager verification signals.",
      fullDescription: "Best-effort verification status check for BM IDs.",
      releaseNotes: "v1.0.0 — Public probe mode.",
      version: "1.0.0",
      toolType: "online" as const,
      onlineRoute: "/tools/check-bm-verified",
      isPublished: true,
      sortOrder: 3,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-link-bm",
      categoryId: "cat-id-tools",
      name: "Check Link BM",
      slug: "check-link-bm",
      shortDescription: "Check BM invitation links Available vs Accepted.",
      fullDescription: "Paste BM invite links (ID|link) and see if still available.",
      releaseNotes: "v1.0.0 — Invite link follower.",
      version: "1.0.0",
      toolType: "online" as const,
      onlineRoute: "/tools/check-link-bm",
      isPublished: true,
      sortOrder: 4,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-bm-name",
      categoryId: "cat-id-tools",
      name: "Check BM Name",
      slug: "check-bm-name",
      shortDescription: "Look up Business Manager display name from BM ID.",
      fullDescription: "Resolve BM display names from public sources when available.",
      releaseNotes: "v1.0.0 — Name resolver.",
      version: "1.0.0",
      toolType: "online" as const,
      onlineRoute: "/tools/check-bm-name",
      isPublished: true,
      sortOrder: 5,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-find-id",
      categoryId: "cat-id-tools",
      name: "Find Facebook ID",
      slug: "find-facebook-id",
      shortDescription: "Extract Facebook IDs from profile, page, group, or post URLs.",
      fullDescription: "Paste Facebook URLs and get numeric IDs via URL parse + public HTML extraction.",
      releaseNotes: "v1.0.0 — URL + HTML ID finder.",
      version: "1.0.0",
      toolType: "online" as const,
      onlineRoute: "/tools/find-facebook-id",
      isPublished: true,
      sortOrder: 6,
      createdAt: ts,
      updatedAt: ts,
    },
    {
      id: "tool-quick-links",
      categoryId: "cat-id-tools",
      name: "Facebook Quick Links",
      slug: "facebook-quick-links",
      shortDescription: "Shortcuts to Ads Manager, Business Settings, and more.",
      fullDescription: "Curated deep links for Facebook Ads and Business Manager pages.",
      releaseNotes: "v1.0.0 — Link pack.",
      version: "1.0.0",
      toolType: "online" as const,
      onlineRoute: "/tools/facebook-quick-links",
      isPublished: true,
      sortOrder: 7,
      createdAt: ts,
      updatedAt: ts,
    },
  ];

  return {
    categories,
    tools,
    products: [
      {
        id: "prod-1",
        name: "Autopay Threshold Method Pack",
        slug: "autopay-threshold-method",
        description:
          "Step-by-step Facebook Autopay Threshold method used by Basictrick community media buyers.",
        priceLabel: "Contact on Telegram",
        isPublished: true,
        sortOrder: 1,
      },
      {
        id: "prod-2",
        name: "Ads Boost Masterclass Notes",
        slug: "ads-boost-notes",
        description: "Practical boosting framework to target $10–100/day earning workflows.",
        priceLabel: "Contact on Telegram",
        isPublished: true,
        sortOrder: 2,
      },
      {
        id: "prod-3",
        name: "Community VIP Access",
        slug: "vip-access",
        description: "Private Telegram VIP channel with daily tips, tools drops, and support.",
        priceLabel: "VIP",
        isPublished: true,
        sortOrder: 3,
      },
    ],
    methods: [
      {
        id: "method-1",
        title: "Facebook Autopay Threshold Basics",
        slug: "autopay-threshold-basics",
        summary: "Understand threshold timing, spend pacing, and account hygiene.",
        content:
          "## Overview\n\nLearn how Autopay Threshold works for Facebook ads accounts, how to pace spend safely, and how Basictrick members structure daily earning workflows ($10–100/day).\n\n## Steps\n\n1. Prepare a clean Business Manager setup.\n2. Warm the account with low spend.\n3. Track threshold notifications.\n4. Scale only after stability.\n\nJoin our Telegram for the full private pack.",
        isPublished: true,
        sortOrder: 1,
        createdAt: ts,
        isNewDrop: true,
        tag: "Autopay",
        level: "Beginner",
        accent: "sky",
      },
      {
        id: "method-2",
        title: "How to Boost Ads Efficiently",
        slug: "boost-ads-efficiently",
        summary: "Creative + audience + budget rules that reduce wasted spend.",
        content:
          "## Boost Framework\n\n1. Use strong creatives (try our Adsterra Image Generator).\n2. Test audiences in small batches.\n3. Kill losers fast, scale winners.\n4. Keep daily reporting in Telegram notes.",
        isPublished: true,
        sortOrder: 2,
        createdAt: ts,
        isNewDrop: true,
        tag: "Boost",
        level: "Pro",
        accent: "rose",
      },
      {
        id: "method-3",
        title: "Daily $10–100 Earning Playbook",
        slug: "daily-earning-playbook",
        summary: "Simple daily routine used by Basictrick media buyers.",
        content:
          "## Daily Routine\n\nMorning: check accounts & BM health.\nMidday: boost winners with fresh creatives.\nNight: log results in Telegram notes.\n\nFull private checklist inside VIP channel.",
        isPublished: true,
        sortOrder: 3,
        createdAt: ts,
        isNewDrop: true,
        tag: "Earning",
        level: "Beginner",
        accent: "emerald",
      },
      {
        id: "method-4",
        title: "BM Hygiene & Limit Protection",
        slug: "bm-hygiene-limits",
        summary: "Keep Business Managers clean and reduce sudden disables.",
        content:
          "## Hygiene Checklist\n\n1. Separate roles properly.\n2. Avoid spammy spending spikes.\n3. Rotate creatives.\n4. Monitor billing health daily.",
        isPublished: true,
        sortOrder: 4,
        createdAt: ts,
        isNewDrop: false,
        tag: "BM",
        level: "Advanced",
        accent: "indigo",
      },
    ],
    settings: {
      siteName: "Basictrick",
      telegramUrl: "https://t.me/basictrick",
      telegramSupport: "https://t.me/basictrick",
      tagline: "Trusted Telegram Community for Facebook Ads Methods & Tools",
      contactEmail: "support@basictrick.com",
      telegramBotToken: "",
      telegramChatId: "",
      sitePublicUrl: "http://localhost:8080",
    },
    accessKeys: [],
  };
}
