/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as MethodRouteImport } from './routes/method'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTelegramRouteImport } from './routes/admin.telegram'
import { Route as ApiAccessRouteImport } from './routes/api.access'
import { Route as ApiToolsRouteImport } from './routes/api.tools'
import { Route as MethodSlugRouteImport } from './routes/method.$slug'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsSlugRouteImport } from './routes/tools.$slug'
import { Route as ToolsAdsterraImageGeneratorRouteImport } from './routes/tools.adsterra-image-generator'
import { Route as ToolsCheckBmNameRouteImport } from './routes/tools.check-bm-name'
import { Route as ToolsCheckBmVerifiedRouteImport } from './routes/tools.check-bm-verified'
import { Route as ToolsCheckLinkBmRouteImport } from './routes/tools.check-link-bm'
import { Route as ToolsCheckLiveBmRouteImport } from './routes/tools.check-live-bm'
import { Route as ToolsCheckLiveUidRouteImport } from './routes/tools.check-live-uid'
import { Route as ToolsFacebookQuickLinksRouteImport } from './routes/tools.facebook-quick-links'
import { Route as ToolsFindFacebookIdRouteImport } from './routes/tools.find-facebook-id'
import { Route as ApiAccessValidateRouteImport } from './routes/api.access.validate'
import { Route as ApiPaymentsZinipayRouteImport } from './routes/api.payments.zinipay'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram.webhook'
import { Route as ApiExtensionLicenseRouteImport } from './routes/api.extension.license'
import { Route as ApiExtensionDownloadRouteImport } from './routes/api.extension.download'
import { Route as ApiPaymentsPlisioWebhookRouteImport } from './routes/api.payments.plisio.webhook'
import { Route as ApiPaymentsZinipayWebhookRouteImport } from './routes/api.payments.zinipay.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/admin/telegram',
  path: '/admin/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessRoute = ApiAccessRouteImport.update({
  id: '/api/access',
  path: '/api/access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiToolsRoute = ApiToolsRouteImport.update({
  id: '/api/tools',
  path: '/api/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodSlugRoute = MethodSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MethodRoute,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSlugRoute = ToolsSlugRouteImport.update({
  id: '/tools/$slug',
  path: '/tools/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsAdsterraImageGeneratorRoute =
  ToolsAdsterraImageGeneratorRouteImport.update({
    id: '/tools/adsterra-image-generator',
    path: '/tools/adsterra-image-generator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsCheckBmNameRoute = ToolsCheckBmNameRouteImport.update({
  id: '/tools/check-bm-name',
  path: '/tools/check-bm-name',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCheckBmVerifiedRoute = ToolsCheckBmVerifiedRouteImport.update({
  id: '/tools/check-bm-verified',
  path: '/tools/check-bm-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCheckLinkBmRoute = ToolsCheckLinkBmRouteImport.update({
  id: '/tools/check-link-bm',
  path: '/tools/check-link-bm',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCheckLiveBmRoute = ToolsCheckLiveBmRouteImport.update({
  id: '/tools/check-live-bm',
  path: '/tools/check-live-bm',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCheckLiveUidRoute = ToolsCheckLiveUidRouteImport.update({
  id: '/tools/check-live-uid',
  path: '/tools/check-live-uid',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFacebookQuickLinksRoute = ToolsFacebookQuickLinksRouteImport.update({
  id: '/tools/facebook-quick-links',
  path: '/tools/facebook-quick-links',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsFindFacebookIdRoute = ToolsFindFacebookIdRouteImport.update({
  id: '/tools/find-facebook-id',
  path: '/tools/find-facebook-id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccessValidateRoute = ApiAccessValidateRouteImport.update({
  id: '/validate',
  path: '/validate',
  getParentRoute: () => ApiAccessRoute,
} as any)
const ApiPaymentsZinipayRoute = ApiPaymentsZinipayRouteImport.update({
  id: '/api/payments/zinipay',
  path: '/api/payments/zinipay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionLicenseRoute = ApiExtensionLicenseRouteImport.update({
  id: '/api/extension/license',
  path: '/api/extension/license',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtensionDownloadRoute = ApiExtensionDownloadRouteImport.update({
  id: '/api/extension/download',
  path: '/api/extension/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsPlisioWebhookRoute =
  ApiPaymentsPlisioWebhookRouteImport.update({
    id: '/api/payments/plisio/webhook',
    path: '/api/payments/plisio/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsZinipayWebhookRoute =
  ApiPaymentsZinipayWebhookRouteImport.update({
    id: '/webhook',
    path: '/webhook',
    getParentRoute: () => ApiPaymentsZinipayRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/method': typeof MethodRouteWithChildren
  '/shop': typeof ShopRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/api/access': typeof ApiAccessRouteWithChildren
  '/api/tools': typeof ApiToolsRoute
  '/method/$slug': typeof MethodSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/adsterra-image-generator': typeof ToolsAdsterraImageGeneratorRoute
  '/tools/check-bm-name': typeof ToolsCheckBmNameRoute
  '/tools/check-bm-verified': typeof ToolsCheckBmVerifiedRoute
  '/tools/check-link-bm': typeof ToolsCheckLinkBmRoute
  '/tools/check-live-bm': typeof ToolsCheckLiveBmRoute
  '/tools/check-live-uid': typeof ToolsCheckLiveUidRoute
  '/tools/facebook-quick-links': typeof ToolsFacebookQuickLinksRoute
  '/tools/find-facebook-id': typeof ToolsFindFacebookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/access/validate': typeof ApiAccessValidateRoute
  '/api/payments/zinipay': typeof ApiPaymentsZinipayRouteWithChildren
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/extension/license': typeof ApiExtensionLicenseRoute
  '/api/extension/download': typeof ApiExtensionDownloadRoute
  '/api/payments/plisio/webhook': typeof ApiPaymentsPlisioWebhookRoute
  '/api/payments/zinipay/webhook': typeof ApiPaymentsZinipayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/method': typeof MethodRouteWithChildren
  '/shop': typeof ShopRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/api/access': typeof ApiAccessRouteWithChildren
  '/api/tools': typeof ApiToolsRoute
  '/method/$slug': typeof MethodSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/adsterra-image-generator': typeof ToolsAdsterraImageGeneratorRoute
  '/tools/check-bm-name': typeof ToolsCheckBmNameRoute
  '/tools/check-bm-verified': typeof ToolsCheckBmVerifiedRoute
  '/tools/check-link-bm': typeof ToolsCheckLinkBmRoute
  '/tools/check-live-bm': typeof ToolsCheckLiveBmRoute
  '/tools/check-live-uid': typeof ToolsCheckLiveUidRoute
  '/tools/facebook-quick-links': typeof ToolsFacebookQuickLinksRoute
  '/tools/find-facebook-id': typeof ToolsFindFacebookIdRoute
  '/admin': typeof AdminIndexRoute
  '/tools': typeof ToolsIndexRoute
  '/api/access/validate': typeof ApiAccessValidateRoute
  '/api/payments/zinipay': typeof ApiPaymentsZinipayRouteWithChildren
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/extension/license': typeof ApiExtensionLicenseRoute
  '/api/extension/download': typeof ApiExtensionDownloadRoute
  '/api/payments/plisio/webhook': typeof ApiPaymentsPlisioWebhookRoute
  '/api/payments/zinipay/webhook': typeof ApiPaymentsZinipayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/license': typeof LicenseRoute
  '/method': typeof MethodRouteWithChildren
  '/shop': typeof ShopRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/api/access': typeof ApiAccessRouteWithChildren
  '/api/tools': typeof ApiToolsRoute
  '/method/$slug': typeof MethodSlugRoute
  '/tools/$slug': typeof ToolsSlugRoute
  '/tools/adsterra-image-generator': typeof ToolsAdsterraImageGeneratorRoute
  '/tools/check-bm-name': typeof ToolsCheckBmNameRoute
  '/tools/check-bm-verified': typeof ToolsCheckBmVerifiedRoute
  '/tools/check-link-bm': typeof ToolsCheckLinkBmRoute
  '/tools/check-live-bm': typeof ToolsCheckLiveBmRoute
  '/tools/check-live-uid': typeof ToolsCheckLiveUidRoute
  '/tools/facebook-quick-links': typeof ToolsFacebookQuickLinksRoute
  '/tools/find-facebook-id': typeof ToolsFindFacebookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tools/': typeof ToolsIndexRoute
  '/api/access/validate': typeof ApiAccessValidateRoute
  '/api/payments/zinipay': typeof ApiPaymentsZinipayRouteWithChildren
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/api/extension/license': typeof ApiExtensionLicenseRoute
  '/api/extension/download': typeof ApiExtensionDownloadRoute
  '/api/payments/plisio/webhook': typeof ApiPaymentsPlisioWebhookRoute
  '/api/payments/zinipay/webhook': typeof ApiPaymentsZinipayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/license'
    | '/method'
    | '/shop'
    | '/admin/telegram'
    | '/api/access'
    | '/api/tools'
    | '/method/$slug'
    | '/tools/$slug'
    | '/tools/adsterra-image-generator'
    | '/tools/check-bm-name'
    | '/tools/check-bm-verified'
    | '/tools/check-link-bm'
    | '/tools/check-live-bm'
    | '/tools/check-live-uid'
    | '/tools/facebook-quick-links'
    | '/tools/find-facebook-id'
    | '/admin/'
    | '/tools/'
    | '/api/access/validate'
    | '/api/payments/zinipay'
    | '/api/telegram/webhook'
    | '/api/extension/license'
    | '/api/extension/download'
    | '/api/payments/plisio/webhook'
    | '/api/payments/zinipay/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/license'
    | '/method'
    | '/shop'
    | '/admin/telegram'
    | '/api/access'
    | '/api/tools'
    | '/method/$slug'
    | '/tools/$slug'
    | '/tools/adsterra-image-generator'
    | '/tools/check-bm-name'
    | '/tools/check-bm-verified'
    | '/tools/check-link-bm'
    | '/tools/check-live-bm'
    | '/tools/check-live-uid'
    | '/tools/facebook-quick-links'
    | '/tools/find-facebook-id'
    | '/admin'
    | '/tools'
    | '/api/access/validate'
    | '/api/payments/zinipay'
    | '/api/telegram/webhook'
    | '/api/extension/license'
    | '/api/extension/download'
    | '/api/payments/plisio/webhook'
    | '/api/payments/zinipay/webhook'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/license'
    | '/method'
    | '/shop'
    | '/admin/telegram'
    | '/api/access'
    | '/api/tools'
    | '/method/$slug'
    | '/tools/$slug'
    | '/tools/adsterra-image-generator'
    | '/tools/check-bm-name'
    | '/tools/check-bm-verified'
    | '/tools/check-link-bm'
    | '/tools/check-live-bm'
    | '/tools/check-live-uid'
    | '/tools/facebook-quick-links'
    | '/tools/find-facebook-id'
    | '/admin/'
    | '/tools/'
    | '/api/access/validate'
    | '/api/payments/zinipay'
    | '/api/telegram/webhook'
    | '/api/extension/license'
    | '/api/extension/download'
    | '/api/payments/plisio/webhook'
    | '/api/payments/zinipay/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LicenseRoute: typeof LicenseRoute
  MethodRoute: typeof MethodRouteWithChildren
  ShopRoute: typeof ShopRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  ApiAccessRoute: typeof ApiAccessRouteWithChildren
  ApiToolsRoute: typeof ApiToolsRoute
  ToolsSlugRoute: typeof ToolsSlugRoute
  ToolsAdsterraImageGeneratorRoute: typeof ToolsAdsterraImageGeneratorRoute
  ToolsCheckBmNameRoute: typeof ToolsCheckBmNameRoute
  ToolsCheckBmVerifiedRoute: typeof ToolsCheckBmVerifiedRoute
  ToolsCheckLinkBmRoute: typeof ToolsCheckLinkBmRoute
  ToolsCheckLiveBmRoute: typeof ToolsCheckLiveBmRoute
  ToolsCheckLiveUidRoute: typeof ToolsCheckLiveUidRoute
  ToolsFacebookQuickLinksRoute: typeof ToolsFacebookQuickLinksRoute
  ToolsFindFacebookIdRoute: typeof ToolsFindFacebookIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
  ApiPaymentsZinipayRoute: typeof ApiPaymentsZinipayRouteWithChildren
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiExtensionLicenseRoute: typeof ApiExtensionLicenseRoute
  ApiExtensionDownloadRoute: typeof ApiExtensionDownloadRoute
  ApiPaymentsPlisioWebhookRoute: typeof ApiPaymentsPlisioWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/admin/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access': {
      id: '/api/access'
      path: '/api/access'
      fullPath: '/api/access'
      preLoaderRoute: typeof ApiAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tools': {
      id: '/api/tools'
      path: '/api/tools'
      fullPath: '/api/tools'
      preLoaderRoute: typeof ApiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method/$slug': {
      id: '/method/$slug'
      path: '/$slug'
      fullPath: '/method/$slug'
      preLoaderRoute: typeof MethodSlugRouteImport
      parentRoute: typeof MethodRoute
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/$slug': {
      id: '/tools/$slug'
      path: '/tools/$slug'
      fullPath: '/tools/$slug'
      preLoaderRoute: typeof ToolsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/adsterra-image-generator': {
      id: '/tools/adsterra-image-generator'
      path: '/tools/adsterra-image-generator'
      fullPath: '/tools/adsterra-image-generator'
      preLoaderRoute: typeof ToolsAdsterraImageGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/check-bm-name': {
      id: '/tools/check-bm-name'
      path: '/tools/check-bm-name'
      fullPath: '/tools/check-bm-name'
      preLoaderRoute: typeof ToolsCheckBmNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/check-bm-verified': {
      id: '/tools/check-bm-verified'
      path: '/tools/check-bm-verified'
      fullPath: '/tools/check-bm-verified'
      preLoaderRoute: typeof ToolsCheckBmVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/check-link-bm': {
      id: '/tools/check-link-bm'
      path: '/tools/check-link-bm'
      fullPath: '/tools/check-link-bm'
      preLoaderRoute: typeof ToolsCheckLinkBmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/check-live-bm': {
      id: '/tools/check-live-bm'
      path: '/tools/check-live-bm'
      fullPath: '/tools/check-live-bm'
      preLoaderRoute: typeof ToolsCheckLiveBmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/check-live-uid': {
      id: '/tools/check-live-uid'
      path: '/tools/check-live-uid'
      fullPath: '/tools/check-live-uid'
      preLoaderRoute: typeof ToolsCheckLiveUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/facebook-quick-links': {
      id: '/tools/facebook-quick-links'
      path: '/tools/facebook-quick-links'
      fullPath: '/tools/facebook-quick-links'
      preLoaderRoute: typeof ToolsFacebookQuickLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/find-facebook-id': {
      id: '/tools/find-facebook-id'
      path: '/tools/find-facebook-id'
      fullPath: '/tools/find-facebook-id'
      preLoaderRoute: typeof ToolsFindFacebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/access/validate': {
      id: '/api/access/validate'
      path: '/validate'
      fullPath: '/api/access/validate'
      preLoaderRoute: typeof ApiAccessValidateRouteImport
      parentRoute: typeof ApiAccessRoute
    }
    '/api/payments/zinipay': {
      id: '/api/payments/zinipay'
      path: '/api/payments/zinipay'
      fullPath: '/api/payments/zinipay'
      preLoaderRoute: typeof ApiPaymentsZinipayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/license': {
      id: '/api/extension/license'
      path: '/api/extension/license'
      fullPath: '/api/extension/license'
      preLoaderRoute: typeof ApiExtensionLicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extension/download': {
      id: '/api/extension/download'
      path: '/api/extension/download'
      fullPath: '/api/extension/download'
      preLoaderRoute: typeof ApiExtensionDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/plisio/webhook': {
      id: '/api/payments/plisio/webhook'
      path: '/api/payments/plisio/webhook'
      fullPath: '/api/payments/plisio/webhook'
      preLoaderRoute: typeof ApiPaymentsPlisioWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/zinipay/webhook': {
      id: '/api/payments/zinipay/webhook'
      path: '/webhook'
      fullPath: '/api/payments/zinipay/webhook'
      preLoaderRoute: typeof ApiPaymentsZinipayWebhookRouteImport
      parentRoute: typeof ApiPaymentsZinipayRoute
    }
  }
}

interface MethodRouteChildren {
  MethodSlugRoute: typeof MethodSlugRoute
}

const MethodRouteChildren: MethodRouteChildren = {
  MethodSlugRoute: MethodSlugRoute,
}

const MethodRouteWithChildren =
  MethodRoute._addFileChildren(MethodRouteChildren)

interface ApiAccessRouteChildren {
  ApiAccessValidateRoute: typeof ApiAccessValidateRoute
}

const ApiAccessRouteChildren: ApiAccessRouteChildren = {
  ApiAccessValidateRoute: ApiAccessValidateRoute,
}

const ApiAccessRouteWithChildren = ApiAccessRoute._addFileChildren(
  ApiAccessRouteChildren,
)

interface ApiPaymentsZinipayRouteChildren {
  ApiPaymentsZinipayWebhookRoute: typeof ApiPaymentsZinipayWebhookRoute
}

const ApiPaymentsZinipayRouteChildren: ApiPaymentsZinipayRouteChildren = {
  ApiPaymentsZinipayWebhookRoute: ApiPaymentsZinipayWebhookRoute,
}

const ApiPaymentsZinipayRouteWithChildren =
  ApiPaymentsZinipayRoute._addFileChildren(ApiPaymentsZinipayRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LicenseRoute: LicenseRoute,
  MethodRoute: MethodRouteWithChildren,
  ShopRoute: ShopRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  ApiAccessRoute: ApiAccessRouteWithChildren,
  ApiToolsRoute: ApiToolsRoute,
  ToolsSlugRoute: ToolsSlugRoute,
  ToolsAdsterraImageGeneratorRoute: ToolsAdsterraImageGeneratorRoute,
  ToolsCheckBmNameRoute: ToolsCheckBmNameRoute,
  ToolsCheckBmVerifiedRoute: ToolsCheckBmVerifiedRoute,
  ToolsCheckLinkBmRoute: ToolsCheckLinkBmRoute,
  ToolsCheckLiveBmRoute: ToolsCheckLiveBmRoute,
  ToolsCheckLiveUidRoute: ToolsCheckLiveUidRoute,
  ToolsFacebookQuickLinksRoute: ToolsFacebookQuickLinksRoute,
  ToolsFindFacebookIdRoute: ToolsFindFacebookIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
  ApiPaymentsZinipayRoute: ApiPaymentsZinipayRouteWithChildren,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiExtensionLicenseRoute: ApiExtensionLicenseRoute,
  ApiExtensionDownloadRoute: ApiExtensionDownloadRoute,
  ApiPaymentsPlisioWebhookRoute: ApiPaymentsPlisioWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
